### ISSUE TITLE
Internal server error when querying orders

### ISSUE THREAD

**Issue by wildcant** [wp-graphql/wp-graphql-woocommerce#718]
**Describe the bug**
Getting `Internal server error` as response to simple `orders` query. 

| This is the `docker-compose.yml`   |      Are      | 
|----------|:-------------:|
| col 1 is |  left-aligned |

**To Reproduce**
Start a wordpress instance using docker with the command `docker compose up -d`. After docker container starts visit `http://localhost:8000/` and initialize wordpress. Install most recent version of plugins (see plugins versions section), initialize commerce, add products (I used the sample data from `wp-content/plugins/woocommerce/sample-data/sample_products.csv`) and a payment method (I used de default `Cash on delivery`), make an order, try to query to retrieve said order, see error.

<table>
<tr>
<th> Good </th>
<th> Bad </th>
</tr>
<tr>
<td>

```c++
int foo() {
    int result = 4;
    return result;
}
```

</td>
<td>

```c++
int foo() { 
    int x = 4;
    return x;
}
```

</td>
</tr>
</table>
```yml
version: '3'

services:
  # Database
  db:
    platform: linux/x86_64
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - wpsite

  # Wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - '8000:80'
    restart: always
    volumes: ['./src:/var/www/html']
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    networks:
      - wpsite

networks:
  wpsite:
volumes:
  db_data:
```

**Expected behavior**
queries should 
<img width="1058" alt="Screenshot 2023-03-20 at 4 12 08 PM" src="https://user-images.githubusercontent.com/48843517/226466989-7958a2b6-2e14-4273-8ffb-f460a86699e5.png">

**Screenshots**
<img width="1239" alt="Screenshot 2023-03-20 at 4 03 13 PM" src="https://user-images.githubusercontent.com/48843517/226465348-9b6069b0-7059-4952-aa27-8cb3407eaf7f.png">

**Plugin Versions**
WordPress 6.1.1
<img width="909" alt="Screenshot 2023-03-20 at 4 01 45 PM" src="https://user-images.githubusercontent.com/48843517/226465087-24edaf19-fa74-4812-b072-9877c13ee6ce.png">

**Additional context**
